[package]
name = "viva_app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
mongodb = "3.1.1"
serde = { version = "1.0.217", features = ["derive"] }
rand = "0.8.5"
serde_json = "1.0.135"
futures = "0.3.31"
env_logger = "0.11.6"
argon2 = "0.5.3"
async-trait = "0.1.85"
